# Build the Image
FROM golang:1.19-alpine

WORKDIR /app

COPY ./go.mod ./
#COPY ./go.sum ./

COPY *.go ./

RUN go mod tidy

COPY ./printstuff ./printstuff


# Test the Image

CMD [ "go","test", "elarodas/worker/printstuff" ]

